# Generated by Django 5.2 on 2025-04-09 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='choice date'),
        ),
    ]
